{
 "title": "Redis Novas",
 "description": "Prometheus dashboard for Redis servers",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(redis_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "redis_uptime_in_seconds{instance=\"$host\"}"
    }
   ]
  },
  { "title": "Keyspace stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Number of Successful/Failed lookup of keys",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_keyspace_hits_total{instance=\"$host\"}[1m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(redis_keyspace_misses_total{instance=\"$host\"}[1m])",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Percentage of Successful/Failed lookup of keys",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (rate(redis_keyspace_hits_total{instance=\"$host\"}[1m]) / (rate(redis_keyspace_hits_total{instance=\"$host\"}[1m]) + rate(redis_keyspace_misses_total{instance=\"$host\"}[1m])))",
     "legendFormat": "Success"
    },
    {
     "expr": "100 * (rate(redis_keyspace_misses_total{instance=\"$host\"}[1m]) / (rate(redis_keyspace_hits_total{instance=\"$host\"}[1m]) + rate(redis_keyspace_misses_total{instance=\"$host\"}[1m])))",
     "legendFormat": "Failed"
    }
   ]
  },
  { "title": "Expired/Evicted key stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Expired / Evicted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{instance=\"$host\"}[5m])) by (instance)",
     "legendFormat": "Expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{instance=\"$host\"}[5m])) by (instance)",
     "legendFormat": "Evicted"
    }
   ]
  },
  {
   "title": "Total Items - DB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{instance=\"$host\"})",
     "legendFormat": "{{ db }}"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Total user and system CPU time spent in seconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$host\"}[1m])",
     "legendFormat": "Total CPU time"
    }
   ]
  },
  {
   "title": "System CPU time spent in seconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_cpu_sys_seconds_total{instance=~\"$host\"} [1m])",
     "legendFormat": "Total System CPU time"
    }
   ]
  },
  {
   "title": "User CPU time spent in seconds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_cpu_user_seconds_total{instance=~\"$host\"} [1m])",
     "legendFormat": "User CPU time"
    }
   ]
  },
  {
   "title": "System children CPU time spent in seconds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_cpu_sys_children_seconds_total{instance=~\"$host\"} [1m])",
     "legendFormat": "System children CPU time"
    }
   ]
  },
  {
   "title": "User children CPU time spent in seconds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_cpu_user_children_seconds_total{instance=~\"$host\"} [1m])",
     "legendFormat": "User children CPU time"
    }
   ]
  },
  { "title": "Memory Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Memory Fragmentation ratio",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_mem_fragmentation_ratio{instance=\"$host\"}[1m])",
     "legendFormat": "Memory Fragmentation ratio"
    }
   ]
  },
  {
   "title": "Total Memory Usage percentage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (redis_memory_used_bytes  / redis_config_maxmemory)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Peak Memory Usage percentage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (redis_memory_used_peak_bytes{instance=~\"$host\"}  / redis_config_maxmemory{instance=~\"$host\"} )",
     "legendFormat": "Peak memory"
    }
   ]
  },
  {
   "title": "RSS Memory Usage percentage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (redis_memory_used_rss_bytes{instance=~\"$host\"}  / redis_config_maxmemory{instance=~\"$host\"} )",
     "legendFormat": "RSS memory"
    }
   ]
  },
  {
   "title": "LUA Memory Usage percentage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (redis_memory_used_lua_bytes{instance=~\"$host\"}  / redis_config_maxmemory{instance=~\"$host\"} )",
     "legendFormat": "LUA memory"
    }
   ]
  },
  {
   "title": "Client and connection statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 }
  },
  {
   "title": "Connected clients",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_connected_clients{instance=~\"$host\"}",
     "legendFormat": "Connected clients"
    }
   ]
  },
  {
   "title": "Connected clients - Percentage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (redis_connected_clients{instance=~\"$host\"}/redis_config_maxclients{instance=~\"$host\"})",
     "legendFormat": "Percentage of connected clients"
    }
   ]
  },
  {
   "title": "Blocked clients",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_blocked_clients{instance=~\"$host\"}",
     "legendFormat": "blocked clients"
    }
   ]
  },
  {
   "title": "Rejected connections",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_rejected_connections_total{instance=~\"$host\"}[1m])",
     "legendFormat": "Rejected connections"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{instance=\"$host\"}[5m])",
     "legendFormat": "Input"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{instance=\"$host\"}[5m])",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Operations stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true
  },
  {
   "title": "Commands Executed / sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{instance=\"$host\"}[5m])",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Total amount of time in seconds spent per command - TOP 5",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_duration_seconds_total{instance=~\"$host\"} [1m]))",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Total number of calls per command - TOP 5",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total{instance=\"$host\"}[1m]))",
     "legendFormat": "{{ cmd }}"
    }
   ]
  }
 ]
}